// Generated by CoffeeScript 1.6.3
(function() {
  var onload;

  onload = window.onload;

  window.onload = function(event) {
    var element, trackingElements, _i, _len;
    trackingElements = document.querySelectorAll('[data-track]');
    for (_i = 0, _len = trackingElements.length; _i < _len; _i++) {
      element = trackingElements[_i];
      element.addEventListener('click', function(event) {
        var tracking;
        tracking = event.target.getAttribute('data-track');
        tracking = tracking.split('/');
        tracking.unshift('event');
        tracking.unshift('send');
        return ga.apply(ga, tracking);
      });
    }
    if (onload != null) {
      return onload(event);
    }
  };

}).call(this);
